### ISSUE TITLE
URGENT: Crashing on `OGC 08-131r3`

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-ogc#3]
```adoc
* [[[OGC08-131r3,OGC 08-131r3]]], The Specification Model – A Standard for Modular Specification (2009)
```

```sh
fetching OGC 08-131r3...
bundler: failed to load command: metanorma (/Users/me/.rbenv/versions/2.6.5/bin/metanorma)
ArgumentError: invalid doctype: policy
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-iso-bib-0.3.12/lib/relaton_iso_bib/iso_bibliographic_item.rb:287:in `check_doctype'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-iso-bib-0.3.12/lib/relaton_iso_bib/iso_bibliographic_item.rb:127:in `initialize'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-ogc-0.1.4/lib/relaton_ogc/scrapper.rb:35:in `new'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-ogc-0.1.4/lib/relaton_ogc/scrapper.rb:35:in `parse_page'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-ogc-0.1.4/lib/relaton_ogc/hit.rb:9:in `fetch'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-ogc-0.1.4/lib/relaton_ogc/ogc_bibliography.rb:50:in `block in bib_results_filter'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-ogc-0.1.4/lib/relaton_ogc/ogc_bibliography.rb:49:in `each'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-ogc-0.1.4/lib/relaton_ogc/ogc_bibliography.rb:49:in `bib_results_filter'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-ogc-0.1.4/lib/relaton_ogc/ogc_bibliography.rb:23:in `get'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-ogc-0.1.4/lib/relaton_ogc/processor.rb:17:in `get'
  /Users/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/relaton-0.5.19/lib/relaton/db.rb:180:in `new_bib_entry'
```

**Comment by andrew2net** [comment]
@ronaldtse see https://github.com/relaton/relaton-ogc/issues/4#issuecomment-566482199
